services:
  mysql:
    image: mysql:8.0
    container_name: mysql_nisa_phone
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nisa_phone
    restart: unless-stopped
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
    driver: local

networks:
  nisa_network:
    driver: bridge